apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "dashd.fullname" . }}
  labels:
    app: {{ template "dashd.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "dashd.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
        - name: {{ template "dashd.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          resources:
  {{ toYaml .Values.resources | indent 10 }}
          ports:
            - name: rpc
              containerPort: {{ .Values.service.rpcPort }}
            - name: p2p
              containerPort: {{ .Values.service.p2pPort }}
            - name: testnet
              containerPort: {{ .Values.service.testnetPort }}
          volumeMounts:
            - name: data
              mountPath: /dash
            {{- if .Values.configurationFile }}
            - name: config
              mountPath: /dash/.dashcore/dash.conf
              subPath: dash.conf
            {{- end }}
      volumes:
        {{- if .Values.configurationFile }}
        - name: config
          configMap:
            name: {{ template "dashd.fullname" . }}
        {{- end }}
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "dashd.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
