{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "gcloud-sqlproxy.labels" . | nindent 4 }}
  name: {{ template "gcloud-sqlproxy.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "gcloud-sqlproxy.selectorLabels" . | nindent 4 }}
{{ .Values.podDisruptionBudget | indent 2 }}
{{- end -}}
