{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "gcloud-sqlproxy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ template "gcloud-sqlproxy.fullname" . }}
{{- end }}
