apiVersion: v1
kind: Service
metadata:
  name: {{ template "gcloud-sqlproxy.fullname" . }}
  labels:
    {{- include "gcloud-sqlproxy.labels" . | nindent 4 }}
spec:
  ports:
  {{- range .Values.cloudsql.instances }}
  - name: {{ .instance }}
    protocol: TCP
    port: {{ .port }}
    targetPort: {{ .instanceShortName | default (.instance | trunc 15) }}
  {{- end }}
  selector:
    {{- include "gcloud-sqlproxy.selectorLabels" . | nindent 4 }}
