apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bitcoincashd.fullname" . }}
  labels:
    app: {{ template "bitcoincashd.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.configurationFile | indent 2 }}
