image:
  repository: "ethereum/client-go"
  tag: "stable"
  pullPolicy: IfNotPresent

rpcPort: 8545
wsPort: 8546
rpcApi: "net,eth,personal,web3"
rpcVhosts: "*"
wsApi: "net,eth,personal,web3"
wsOrigins: "*"
networkId: 1
testnet: false
rinkeby: false
syncMode: "fast"
customArgs: {}
#  cache: 1024
#  debug:
#  maxpeers: 128

persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 300Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
#   limit:
#     memory: 1000Mi
#     cpu: 300m
