name: gcloud-sqlproxy
version: 0.7.0
appVersion: 1.11
description: Google Cloud SQL Proxy
keywords:
- google
- cloud
- postgresql
- mysql
- sql
- sqlproxy
home: https://cloud.google.com/sql/docs/postgres/sql-proxy
sources:
- https://github.com/rimusz/charts
- https://github.com/dysnix/helm-charts
deprecated: false
